/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as QualityRouteImport } from './routes/quality'
import { Route as NewsRouteImport } from './routes/news'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FactoryRouteImport } from './routes/factory'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CertificationsRouteImport } from './routes/certifications'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as SolutionsSlugRouteImport } from './routes/solutions.$slug'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as ProductsCategoryIdIndexRouteImport } from './routes/products.$categoryId.index'
import { Route as ProductsCategoryIdProductIdRouteImport } from './routes/products.$categoryId.$productId'

const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityRoute = QualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FactoryRoute = FactoryRouteImport.update({
  id: '/factory',
  path: '/factory',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationsRoute = CertificationsRouteImport.update({
  id: '/certifications',
  path: '/certifications',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsSlugRoute = SolutionsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SolutionsRoute,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsCategoryIdIndexRoute = ProductsCategoryIdIndexRouteImport.update({
  id: '/products/$categoryId/',
  path: '/products/$categoryId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsCategoryIdProductIdRoute =
  ProductsCategoryIdProductIdRouteImport.update({
    id: '/products/$categoryId/$productId',
    path: '/products/$categoryId/$productId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/catalog': typeof CatalogRoute
  '/certifications': typeof CertificationsRoute
  '/contact': typeof ContactRoute
  '/downloads': typeof DownloadsRoute
  '/factory': typeof FactoryRoute
  '/faq': typeof FaqRoute
  '/news': typeof NewsRoute
  '/quality': typeof QualityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/p/$slug': typeof PSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/products/': typeof ProductsIndexRoute
  '/products/$categoryId/$productId': typeof ProductsCategoryIdProductIdRoute
  '/products/$categoryId/': typeof ProductsCategoryIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/catalog': typeof CatalogRoute
  '/certifications': typeof CertificationsRoute
  '/contact': typeof ContactRoute
  '/downloads': typeof DownloadsRoute
  '/factory': typeof FactoryRoute
  '/faq': typeof FaqRoute
  '/news': typeof NewsRoute
  '/quality': typeof QualityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/p/$slug': typeof PSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/products': typeof ProductsIndexRoute
  '/products/$categoryId/$productId': typeof ProductsCategoryIdProductIdRoute
  '/products/$categoryId': typeof ProductsCategoryIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/catalog': typeof CatalogRoute
  '/certifications': typeof CertificationsRoute
  '/contact': typeof ContactRoute
  '/downloads': typeof DownloadsRoute
  '/factory': typeof FactoryRoute
  '/faq': typeof FaqRoute
  '/news': typeof NewsRoute
  '/quality': typeof QualityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/p/$slug': typeof PSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/products/': typeof ProductsIndexRoute
  '/products/$categoryId/$productId': typeof ProductsCategoryIdProductIdRoute
  '/products/$categoryId/': typeof ProductsCategoryIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/catalog'
    | '/certifications'
    | '/contact'
    | '/downloads'
    | '/factory'
    | '/faq'
    | '/news'
    | '/quality'
    | '/sitemap.xml'
    | '/solutions'
    | '/p/$slug'
    | '/solutions/$slug'
    | '/products/'
    | '/products/$categoryId/$productId'
    | '/products/$categoryId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/catalog'
    | '/certifications'
    | '/contact'
    | '/downloads'
    | '/factory'
    | '/faq'
    | '/news'
    | '/quality'
    | '/sitemap.xml'
    | '/solutions'
    | '/p/$slug'
    | '/solutions/$slug'
    | '/products'
    | '/products/$categoryId/$productId'
    | '/products/$categoryId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/catalog'
    | '/certifications'
    | '/contact'
    | '/downloads'
    | '/factory'
    | '/faq'
    | '/news'
    | '/quality'
    | '/sitemap.xml'
    | '/solutions'
    | '/p/$slug'
    | '/solutions/$slug'
    | '/products/'
    | '/products/$categoryId/$productId'
    | '/products/$categoryId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CatalogRoute: typeof CatalogRoute
  CertificationsRoute: typeof CertificationsRoute
  ContactRoute: typeof ContactRoute
  DownloadsRoute: typeof DownloadsRoute
  FactoryRoute: typeof FactoryRoute
  FaqRoute: typeof FaqRoute
  NewsRoute: typeof NewsRoute
  QualityRoute: typeof QualityRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SolutionsRoute: typeof SolutionsRouteWithChildren
  PSlugRoute: typeof PSlugRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ProductsCategoryIdProductIdRoute: typeof ProductsCategoryIdProductIdRoute
  ProductsCategoryIdIndexRoute: typeof ProductsCategoryIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality': {
      id: '/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof QualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/factory': {
      id: '/factory'
      path: '/factory'
      fullPath: '/factory'
      preLoaderRoute: typeof FactoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certifications': {
      id: '/certifications'
      path: '/certifications'
      fullPath: '/certifications'
      preLoaderRoute: typeof CertificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/$slug': {
      id: '/solutions/$slug'
      path: '/$slug'
      fullPath: '/solutions/$slug'
      preLoaderRoute: typeof SolutionsSlugRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$categoryId/': {
      id: '/products/$categoryId/'
      path: '/products/$categoryId'
      fullPath: '/products/$categoryId/'
      preLoaderRoute: typeof ProductsCategoryIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$categoryId/$productId': {
      id: '/products/$categoryId/$productId'
      path: '/products/$categoryId/$productId'
      fullPath: '/products/$categoryId/$productId'
      preLoaderRoute: typeof ProductsCategoryIdProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SolutionsRouteChildren {
  SolutionsSlugRoute: typeof SolutionsSlugRoute
}

const SolutionsRouteChildren: SolutionsRouteChildren = {
  SolutionsSlugRoute: SolutionsSlugRoute,
}

const SolutionsRouteWithChildren = SolutionsRoute._addFileChildren(
  SolutionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CatalogRoute: CatalogRoute,
  CertificationsRoute: CertificationsRoute,
  ContactRoute: ContactRoute,
  DownloadsRoute: DownloadsRoute,
  FactoryRoute: FactoryRoute,
  FaqRoute: FaqRoute,
  NewsRoute: NewsRoute,
  QualityRoute: QualityRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SolutionsRoute: SolutionsRouteWithChildren,
  PSlugRoute: PSlugRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ProductsCategoryIdProductIdRoute: ProductsCategoryIdProductIdRoute,
  ProductsCategoryIdIndexRoute: ProductsCategoryIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
