/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsCategoryIdRouteImport } from './routes/products.$categoryId'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as ProductsCategoryIdProductIdRouteImport } from './routes/products.$categoryId.$productId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsCategoryIdRoute = ProductsCategoryIdRouteImport.update({
  id: '/products/$categoryId',
  path: '/products/$categoryId',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsCategoryIdProductIdRoute =
  ProductsCategoryIdProductIdRouteImport.update({
    id: '/$productId',
    path: '/$productId',
    getParentRoute: () => ProductsCategoryIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/catalog': typeof CatalogRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/p/$slug': typeof PSlugRoute
  '/products/$categoryId': typeof ProductsCategoryIdRouteWithChildren
  '/products/': typeof ProductsIndexRoute
  '/products/$categoryId/$productId': typeof ProductsCategoryIdProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/catalog': typeof CatalogRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/p/$slug': typeof PSlugRoute
  '/products/$categoryId': typeof ProductsCategoryIdRouteWithChildren
  '/products': typeof ProductsIndexRoute
  '/products/$categoryId/$productId': typeof ProductsCategoryIdProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/catalog': typeof CatalogRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/p/$slug': typeof PSlugRoute
  '/products/$categoryId': typeof ProductsCategoryIdRouteWithChildren
  '/products/': typeof ProductsIndexRoute
  '/products/$categoryId/$productId': typeof ProductsCategoryIdProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/catalog'
    | '/contact'
    | '/sitemap.xml'
    | '/p/$slug'
    | '/products/$categoryId'
    | '/products/'
    | '/products/$categoryId/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/catalog'
    | '/contact'
    | '/sitemap.xml'
    | '/p/$slug'
    | '/products/$categoryId'
    | '/products'
    | '/products/$categoryId/$productId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/catalog'
    | '/contact'
    | '/sitemap.xml'
    | '/p/$slug'
    | '/products/$categoryId'
    | '/products/'
    | '/products/$categoryId/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CatalogRoute: typeof CatalogRoute
  ContactRoute: typeof ContactRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  PSlugRoute: typeof PSlugRoute
  ProductsCategoryIdRoute: typeof ProductsCategoryIdRouteWithChildren
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$categoryId': {
      id: '/products/$categoryId'
      path: '/products/$categoryId'
      fullPath: '/products/$categoryId'
      preLoaderRoute: typeof ProductsCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$categoryId/$productId': {
      id: '/products/$categoryId/$productId'
      path: '/$productId'
      fullPath: '/products/$categoryId/$productId'
      preLoaderRoute: typeof ProductsCategoryIdProductIdRouteImport
      parentRoute: typeof ProductsCategoryIdRoute
    }
  }
}

interface ProductsCategoryIdRouteChildren {
  ProductsCategoryIdProductIdRoute: typeof ProductsCategoryIdProductIdRoute
}

const ProductsCategoryIdRouteChildren: ProductsCategoryIdRouteChildren = {
  ProductsCategoryIdProductIdRoute: ProductsCategoryIdProductIdRoute,
}

const ProductsCategoryIdRouteWithChildren =
  ProductsCategoryIdRoute._addFileChildren(ProductsCategoryIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CatalogRoute: CatalogRoute,
  ContactRoute: ContactRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  PSlugRoute: PSlugRoute,
  ProductsCategoryIdRoute: ProductsCategoryIdRouteWithChildren,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
